CREATE TABLE USERS (
    user_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username TEXT NOT NULL,
    first_name TEXT NOT NULL,
    middle_name TEXT NOT NULL,
    last_name TEXT NOT NULL
);

CREATE TABLE POSTS (
    post_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    content TEXT,
    tags TEXT,
    user_id VARCHAR(255) NOT NULL,
    likes INTEGER,
    dislikes INTEGER,
    create_date DATETIME,
    update_date DATETIME
);

CREATE TABLE COMMENTS (
    comment_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    post_id INTEGER NOT NULL,
    content TEXT,
    user_id VARCHAR(255) NOT NULL,
    likes INTEGER,
    dislikes INTEGER,
    create_date DATETIME,
    update_date DATETIME
);

ALTER TABLE COMMENTS
ADD FOREIGN KEY (post_id) REFERENCES POSTS(post_id);

CREATE UNIQUE INDEX USERS_INDEX
ON USERS (user_id);

CREATE UNIQUE INDEX POSTS_INDEX
ON POSTS (post_id, user_id);

CREATE UNIQUE INDEX COMMENTS_INDEX
ON COMMENTS (comment_id, post_id, user_id);

CREATE TRIGGER CREATE_DATE_POSTS_BI_TGR BEFORE INSERT ON POSTS
       FOR EACH ROW SET NEW.create_date = NOW();

CREATE TRIGGER CREATE_DATE_COMMENTS_BI_TGR BEFORE INSERT ON COMMENTS
       FOR EACH ROW SET NEW.create_date = NOW();

CREATE TRIGGER UPDATE_DATE_POSTS_BU_TGR BEFORE UPDATE ON POSTS
       FOR EACH ROW SET NEW.update_date = NOW();

CREATE TRIGGER UPDATE_DATE_COMMENTS_BU_TGR BEFORE UPDATE ON COMMENTS
       FOR EACH ROW SET NEW.update_date = NOW();